# 2016 October 21
# https://github.com/bevry/base

# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "4"
  - "6"
cache:
  directories:
    - node_modules

# Prepare our tests
before_install: if test "$(npm --version)" != "$(npm view npm version)"; then npm install -g npm; fi
before_script: "npm run compile"

# Run our tests
script: "npm test"

# Custom notifications
notifications:
  slack:
    secure: E3UE+ZnKFBHYhAcDdognqoUXGpOa55haO8JyPG+TYpWPshbPkqz9k7My33cwhJv3GU4mnkAAJ7qnDvYSMAPbC5m6C4X779dEwrkrEmGjxpqK03fg3XpcK73M3MfvN/dZzLJ6xm1SlcVv9srYXtjeMIscgqa9exlARy8UqaqSggw=
  email:
    recipients:
      secure: M6BTfFYSqLYxK069Myv/rwG8UvVOKNQiFyWNRAdYQ1lfvzZ5F2+fLNwqdyaypZwodf6QLjntGcwcF/scTsUFil1hPixbR7TBFo+Kdh19xGRmXIIx5DGO3SaOLmk7eKZeZG9V/0Zy/cDclkCGLoNfWm6O1LU7jgfyoT6Wln5LBj4=
